---
version: "3.7"
services:
  nautobot:
    image: "networktocode/nautobot:${NAUTOBOT_IMAGE:-1.5.11}-py${PYTHON_VER:-3.9}"
    env_file:
      - "local.env"
    ports:
      - "8443:8443"
      - "8080:8080"
    restart: "unless-stopped"
  # ----------------------------------
  # Celery worker must only be used in > 1.1.0 installs. If setting to a previous install, remove this worker
  # ----------------------------------
  celery_worker:
    image: "networktocode/nautobot:${NAUTOBOT_IMAGE:-1.5.11}-py${PYTHON_VER:-3.9}"
    entrypoint: "sh -c 'nautobot-server celery worker -l $$NAUTOBOT_LOG_LEVEL'"
    healthcheck:
      interval: "5s"
      timeout: "5s"
      start_period: "5s"
      retries: 3
      test: ["CMD", "nautobot-server", "health_check"]
    depends_on:
      - "nautobot"
      - "redis"
    env_file:
      - "./local.env"
    tty: true
  # ----------------------------------
  # Celery beat must only be used in > 1.2.0 installs. If setting to a previous install, remove this worker
  # ----------------------------------
  celery_beat:
    image: "networktocode/nautobot:${NAUTOBOT_IMAGE:-1.5.11}-py${PYTHON_VER:-3.9}"
    entrypoint: "sh -c 'nautobot-server celery beat -l $$NAUTOBOT_LOG_LEVEL'"
    healthcheck:
      interval: "5s"
      timeout: "5s"
      start_period: "5s"
      retries: 3
      test: ["CMD", "nautobot-server", "health_check"]
    depends_on:
      - "nautobot"
      - "redis"
    env_file:
      - "./local.env"
    tty: true
  redis:
    image: "redis:alpine"
    env_file:
      - "local.env"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD"  ## $$ because of docker-compose
    restart: "unless-stopped"
  db:
    image: "postgres:13"
    # Apple Silicon has issues with Postgres14, there is no needed functions to get to Postgres14 for Nautobot to work.
    env_file:
      - "local.env"
    environment:
      NAUTOBOT_DB_ENGINE: "django.db.backends.postgres"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    restart: "unless-stopped"
volumes:
  db_data:
