---
version: "3.7"
services:
  # web:
  #   image: "nginx:stable"
  #   depends_on:
  #     - nautobot
  #   ports:
  #     - "8443:8443"
  #     - "8080:8080"
  #   volumes:
  #     - "./nginx.conf:/etc/nginx/nginx.conf"
  #     - "$PWD/certs/nginx-selfsigned.crt:/etc/ssl/certs/nautobot.crt"
  #     - "$PWD/certs/nginx-selfsigned.key:/etc/ssl/private/nautobot.key"
  nautobot:
    image: "nniehoff/nautobot:v0.0.5"
    env_file:
      - ".env"
    ports:
      - "8443:8443"
      - "8080:8080"
  nautobot-worker:
    image: "nniehoff/nautobot:v0.0.5"
    env_file:
      - ".env"
    entrypoint: "nautobot-server rqworker"
    depends_on:
      - nautobot
  redis-cacheops:
    image: "redis:alpine"
    env_file:
      - ".env"
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD  ## $$ because of docker-compose
  redis-queue:
    image: "redis:alpine"
    env_file:
      - ".env"
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$NAUTOBOT_REDIS_PASSWORD  ## $$ because of docker-compose
  postgres:
    image: postgres:10
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
